version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

workflows:
  pull-request:
    jobs:
      - build-and-test